# This workflow will run all test cases

name: Automated Login Tests

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
#   workflow_dispatch:
#   schedule:
#     - cron: '0 1 * * 1-5'  # Runs every 9AM in Asia/Manila timezone from Monday to Friday

permissions:
 contents: read

jobs:
 login_tests:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Set up Python 3.10
     uses: actions/setup-python@v3
     with:
       python-version: "3.10"
      
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install robotframework
       pip install robotframework-seleniumlibrary
       pip install robotframework-requests
       pip install robotframework-browser
       pip install robotframework-jsonlibrary
       pip install robotframework-csvlibrary
       pip install pyotp
       # The following is only needed if you use Browser library tests
       rfbrowser init 

   - name: Run Sample Verification Tests
     id: robot_test
     run: |
       robot -d output -x junit-report.xml TEST/test.robot
       echo "exit_code=$?" >> $GITHUB_OUTPUT

   - name: Set the date and time
     run: |
       echo "START_TIME=$(TZ=":Asia/Singapore" date -R|sed 's/.....$//')" >> $GITHUB_ENV

   - name: Upload test results
     if: always()
     uses: actions/upload-artifact@v4
     with:
       name: robot-test-results
       path: |
         output/
         junit-report.xml

   - name: Check test status
     if: steps.robot_test.outputs.exit_code != '0'
     run: |
       echo "Robot Framework tests failed with exit code ${{ steps.robot_test.outputs.exit_code }}"
       exit ${{ steps.robot_test.outputs.exit_code }}